### ISSUE TITLE
skimage.draw.circle is removed in versions 0.19 and greater

### ISSUE THREAD

**Issue by espandre** [TDT4195-tutorial/TDT4195-StarterCode#1]
The function `skimage.draw.circle(...)` has been [removed from scikit-image starting with version 0.19](https://scikit-image.org/docs/0.18.x/api/skimage.draw.html#circle), which is the default when installed through pip. The deprecation happened in version 0.17 of scikit-image, which also introduced the replacement.

Per the [scikit-image documentation](https://scikit-image.org/docs/stable/api/skimage.draw.html#disk), `skimage.draw.disk(...)` is the replacement 

Affected code:
https://github.com/TDT4195-tutorial/TDT4195-StarterCode/blob/f14d34ae2d62c0fb42a9b66797d01badf51aaa90/assignment%202/utils.py#L130

**Comment by mbirkhez** [comment]
The code is updated now :)
